window.onload = function() {
    var cy = cytoscape({
    container: document.getElementById('cy'), // container to render in


  elements: [ // list of graph elements to start with
    {'data': {'id': 'Coffee'}},
 {'data': {'id': 'Sandwich'}},
 {'data': {'id': 'Flavored-Lattes'}},
 {'data': {'id': 'Soup'}},
 {'data': {'id': 'flavmilkespresso'}},
 {'data': {'id': 'Lunch-Specials'}},
 {'data': {'id': 'Cookies'}},
 {'data': {'id': 'Scone'}},
 {'data': {'id': 'Brownies'}},
 {'data': {'id': 'Any'}},

 {'data': {'id': 'Coffee_Scone', 'source': 'Coffee', 'target': 'Scone'}},
 {'data': {'id': 'Coffee_Any', 'source': 'Coffee', 'target': 'Any'}},
 {'data': {'id': 'Lunch-Specials_Any',
   'source': 'Lunch-Specials',
   'target': 'Any'}},
 {'data': {'id': 'Soup_Flavored-Lattes',
   'source': 'Soup',
   'target': 'Flavored-Lattes'}},
 {'data': {'id': 'Brownies_Soup', 'source': 'Brownies', 'target': 'Soup'}},
 {'data': {'id': 'Lunch-Specials_Cookies',
   'source': 'Lunch-Specials',
   'target': 'Cookies'}},
 {'data': {'id': 'Coffee_Sandwich', 'source': 'Coffee', 'target': 'Sandwich'}},
 {'data': {'id': 'Lunch-Specials_Scone',
   'source': 'Lunch-Specials',
   'target': 'Scone'}},
 {'data': {'id': 'Flavored-Lattes_Coffee',
   'source': 'Flavored-Lattes',
   'target': 'Coffee'}},
 {'data': {'id': 'Cookies_flavmilkespresso',
   'source': 'Cookies',
   'target': 'flavmilkespresso'}},
 {'data': {'id': 'Lunch-Specials_Sandwich',
   'source': 'Lunch-Specials',
   'target': 'Sandwich'}},
 {'data': {'id': 'Scone_Flavored-Lattes',
   'source': 'Scone',
   'target': 'Flavored-Lattes'}},
 {'data': {'id': 'Coffee_Cookies', 'source': 'Coffee', 'target': 'Cookies'}},
 {'data': {'id': 'Sandwich_Scone', 'source': 'Sandwich', 'target': 'Scone'}},
 {'data': {'id': 'Coffee_Brownies', 'source': 'Coffee', 'target': 'Brownies'}},
 {'data': {'id': 'Scone_Any', 'source': 'Scone', 'target': 'Any'}},
 {'data': {'id': 'Flavored-Lattes_Sandwich',
   'source': 'Flavored-Lattes',
   'target': 'Sandwich'}},
 {'data': {'id': 'Brownies_Sandwich',
   'source': 'Brownies',
   'target': 'Sandwich'}},
 {'data': {'id': 'Cookies_Scone', 'source': 'Cookies', 'target': 'Scone'}},
 {'data': {'id': 'Cookies_Any', 'source': 'Cookies', 'target': 'Any'}},
 {'data': {'id': 'Flavored-Lattes_flavmilkespresso',
   'source': 'Flavored-Lattes',
   'target': 'flavmilkespresso'}},
 {'data': {'id': 'Lunch-Specials_Flavored-Lattes',
   'source': 'Lunch-Specials',
   'target': 'Flavored-Lattes'}},
 {'data': {'id': 'Soup_Scone', 'source': 'Soup', 'target': 'Scone'}},
 {'data': {'id': 'Any_Flavored-Lattes',
   'source': 'Any',
   'target': 'Flavored-Lattes'}},
 {'data': {'id': 'flavmilkespresso_Lunch-Specials',
   'source': 'flavmilkespresso',
   'target': 'Lunch-Specials'}},
 {'data': {'id': 'Lunch-Specials_Coffee',
   'source': 'Lunch-Specials',
   'target': 'Coffee'}},
 {'data': {'id': 'Soup_Coffee', 'source': 'Soup', 'target': 'Coffee'}},
 {'data': {'id': 'Scone_flavmilkespresso',
   'source': 'Scone',
   'target': 'flavmilkespresso'}},
 {'data': {'id': 'Scone_Brownies', 'source': 'Scone', 'target': 'Brownies'}},
 {'data': {'id': 'Cookies_Sandwich',
   'source': 'Cookies',
   'target': 'Sandwich'}},
 {'data': {'id': 'Sandwich_flavmilkespresso',
   'source': 'Sandwich',
   'target': 'flavmilkespresso'}},
 {'data': {'id': 'flavmilkespresso_Brownies',
   'source': 'flavmilkespresso',
   'target': 'Brownies'}},
 {'data': {'id': 'Any_Brownies', 'source': 'Any', 'target': 'Brownies'}},
 {'data': {'id': 'Flavored-Lattes_Cookies',
   'source': 'Flavored-Lattes',
   'target': 'Cookies'}},
 {'data': {'id': 'Any_Soup', 'source': 'Any', 'target': 'Soup'}},
 {'data': {'id': 'Lunch-Specials_Brownies',
   'source': 'Lunch-Specials',
   'target': 'Brownies'}},
 {'data': {'id': 'Brownies_Flavored-Lattes',
   'source': 'Brownies',
   'target': 'Flavored-Lattes'}},
 {'data': {'id': 'Lunch-Specials_Soup',
   'source': 'Lunch-Specials',
   'target': 'Soup'}},
 {'data': {'id': 'Coffee_flavmilkespresso',
   'source': 'Coffee',
   'target': 'flavmilkespresso'}},
 {'data': {'id': 'flavmilkespresso_Soup',
   'source': 'flavmilkespresso',
   'target': 'Soup'}},
 {'data': {'id': 'flavmilkespresso_Any',
   'source': 'flavmilkespresso',
   'target': 'Any'}},
 {'data': {'id': 'Sandwich_Any', 'source': 'Sandwich', 'target': 'Any'}},
 {'data': {'id': 'Cookies_Brownies',
   'source': 'Cookies',
   'target': 'Brownies'}},
 {'data': {'id': 'Sandwich_Soup', 'source': 'Sandwich', 'target': 'Soup'}},
 {'data': {'id': 'Cookies_Soup', 'source': 'Cookies', 'target': 'Soup'}}



  ],

  style: [ // the stylesheet for the graph
    {
      selector: 'node',
      style: {
        'background-color': '#666',
        'label': 'data(id)',
        'width' : 30
      }
    },

    {
      selector: 'edge',
      style: {
        'width': 3,
        'line-color': '#ccc',
        'target-arrow-color': '#ccc',
        'target-arrow-shape': 'triangle'
      }
    },
    {'selector': 'node#Coffee', 'style': {'height': 30, 'width': 30}},
 {'selector': 'node#Sandwich', 'style': {'height': 25, 'width': 25}},
 {'selector': 'node#Flavored-Lattes', 'style': {'height': 24, 'width': 24}},
 {'selector': 'node#Soup', 'style': {'height': 23, 'width': 23}},
 {'selector': 'node#flavmilkespresso', 'style': {'height': 23, 'width': 23}},
 {'selector': 'node#Lunch-Specials', 'style': {'height': 23, 'width': 23}},
 {'selector': 'node#Cookies', 'style': {'height': 23, 'width': 23}},
 {'selector': 'node#Scone', 'style': {'height': 22, 'width': 22}},
 {'selector': 'node#Brownies', 'style': {'height': 22, 'width': 22}},
 {'selector': 'node#Any', 'style': {'height': 20, 'width': 20}},

{'selector': 'edge#Coffee_Scone', 'style': {'width': 7}},
 {'selector': 'edge#Coffee_Any', 'style': {'width': 6}},
 {'selector': 'edge#Lunch-Specials_Any', 'style': {'width': 1}},
 {'selector': 'edge#Soup_Flavored-Lattes', 'style': {'width': 2}},
 {'selector': 'edge#Brownies_Soup', 'style': {'width': 2}},
 {'selector': 'edge#Lunch-Specials_Cookies', 'style': {'width': 2}},
 {'selector': 'edge#Coffee_Sandwich', 'style': {'width': 6}},
 {'selector': 'edge#Lunch-Specials_Scone', 'style': {'width': 1}},
 {'selector': 'edge#Flavored-Lattes_Coffee', 'style': {'width': 2}},
 {'selector': 'edge#Cookies_flavmilkespresso', 'style': {'width': 2}},
 {'selector': 'edge#Lunch-Specials_Sandwich', 'style': {'width': 3}},
 {'selector': 'edge#Scone_Flavored-Lattes', 'style': {'width': 2}},
 {'selector': 'edge#Coffee_Cookies', 'style': {'width': 6}},
 {'selector': 'edge#Sandwich_Scone', 'style': {'width': 2}},
 {'selector': 'edge#Coffee_Brownies', 'style': {'width': 4}},
 {'selector': 'edge#Scone_Any', 'style': {'width': 1}},
 {'selector': 'edge#Flavored-Lattes_Sandwich', 'style': {'width': 3}},
 {'selector': 'edge#Brownies_Sandwich', 'style': {'width': 3}},
 {'selector': 'edge#Cookies_Scone', 'style': {'width': 3}},
 {'selector': 'edge#Cookies_Any', 'style': {'width': 1}},
 {'selector': 'edge#Flavored-Lattes_flavmilkespresso', 'style': {'width': 5}},
 {'selector': 'edge#Lunch-Specials_Flavored-Lattes', 'style': {'width': 2}},
 {'selector': 'edge#Soup_Scone', 'style': {'width': 2}},
 {'selector': 'edge#Any_Flavored-Lattes', 'style': {'width': 2}},
 {'selector': 'edge#flavmilkespresso_Lunch-Specials', 'style': {'width': 1}},
 {'selector': 'edge#Lunch-Specials_Coffee', 'style': {'width': 5}},
 {'selector': 'edge#Soup_Coffee', 'style': {'width': 5}},
 {'selector': 'edge#Scone_flavmilkespresso', 'style': {'width': 2}},
 {'selector': 'edge#Scone_Brownies', 'style': {'width': 2}},
 {'selector': 'edge#Cookies_Sandwich', 'style': {'width': 3}},
 {'selector': 'edge#Sandwich_flavmilkespresso', 'style': {'width': 2}},
 {'selector': 'edge#flavmilkespresso_Brownies', 'style': {'width': 2}},
 {'selector': 'edge#Any_Brownies', 'style': {'width': 1}},
 {'selector': 'edge#Flavored-Lattes_Cookies', 'style': {'width': 2}},
 {'selector': 'edge#Any_Soup', 'style': {'width': 1}},
 {'selector': 'edge#Lunch-Specials_Brownies', 'style': {'width': 1}},
 {'selector': 'edge#Brownies_Flavored-Lattes', 'style': {'width': 2}},
 {'selector': 'edge#Lunch-Specials_Soup', 'style': {'width': 1}},
 {'selector': 'edge#Coffee_flavmilkespresso', 'style': {'width': 4}},
 {'selector': 'edge#flavmilkespresso_Soup', 'style': {'width': 1}},
 {'selector': 'edge#flavmilkespresso_Any', 'style': {'width': 2}},
 {'selector': 'edge#Sandwich_Any', 'style': {'width': 1}},
 {'selector': 'edge#Cookies_Brownies', 'style': {'width': 3}},
 {'selector': 'edge#Sandwich_Soup', 'style': {'width': 3}},
 {'selector': 'edge#Cookies_Soup', 'style': {'width': 2}}

    
  ],

  layout: {
    name: 'circle',
  }

});
};
